export type MenuItem = {
  id: number
  name: string
  category: string
  region: "Africa" | "Asia" | "Europe" | "Middle East" | "Americas"
  course: "main" | "dessert" | "drink"
  description: string
  price: string
  image: string
  dietary: string[]
  customizations: string[]
}

export const menuItems: MenuItem[] = [
  // Africa
  {
    id: 1,
    name: "Jollof Rice & Grilled Chicken",
    category: "West African",
    region: "Africa",
    course: "main",
    description: "Smoky jollof rice with grilled chicken and ripe plantain.",
    price: "$14",
    image: "/images/menu/jollof-rice.jpg",
    dietary: ["spicy"],
    customizations: ["Mild/Hot Pepper", "Extra Plantain", "No Onion"],
  },
  {
    id: 2,
    name: "Egusi Soup & Pounded Yam",
    category: "West African",
    region: "Africa",
    course: "main",
    description: "Traditional melon-seed soup with assorted protein and greens.",
    price: "$18",
    image: "/images/menu/egusi-pounded-yam.jpg",
    dietary: ["gluten-free"],
    customizations: ["Goat/Fish/Chicken", "No Crayfish", "Extra Greens"],
  },
  {
    id: 3,
    name: "Puff-Puff Trio",
    category: "West African Dessert",
    region: "Africa",
    course: "dessert",
    description: "Golden puff-puff with chocolate, vanilla, and caramel dips.",
    price: "$8",
    image: "/images/menu/puff-puff.avif",
    dietary: ["vegetarian"],
    customizations: ["Extra Dip", "No Cinnamon", "Dusting Sugar"],
  },
  {
    id: 4,
    name: "Coconut Chin Chin Parfait",
    category: "West African Dessert",
    region: "Africa",
    course: "dessert",
    description: "Crunchy chin chin layered with coconut cream and nuts.",
    price: "$9",
    image: "/images/menu/chin-chin-parfait.jpg",
    dietary: ["vegetarian"],
    customizations: ["No Nuts", "Extra Coconut", "Caramel Drizzle"],
  },
  {
    id: 5,
    name: "Zobo Cooler",
    category: "West African Drink",
    region: "Africa",
    course: "drink",
    description: "Chilled hibiscus and pineapple drink with ginger.",
    price: "$6",
    image: "/images/menu/zobo-sorbet.jpg",
    dietary: ["non-alcoholic", "gluten-free"],
    customizations: ["Low Sugar", "Extra Ginger", "No Clove"],
  },
  {
    id: 6,
    name: "Tiger Nut Milk",
    category: "West African Drink",
    region: "Africa",
    course: "drink",
    description: "Creamy tiger nut milk infused with dates and cinnamon.",
    price: "$7",
    image: "",
    dietary: ["non-alcoholic", "gluten-free"],
    customizations: ["Cold/Room Temp", "Extra Date", "No Cinnamon"],
  },

  // Asia
  {
    id: 7,
    name: "Pad Thai",
    category: "Thai",
    region: "Asia",
    course: "main",
    description: "Rice noodles with tamarind sauce, peanuts, and lime.",
    price: "$14",
    image: "/images/menu/pad-thai.jpg",
    dietary: ["spicy"],
    customizations: ["Tofu/Chicken/Shrimp", "No Peanuts", "Extra Chili"],
  },
  {
    id: 8,
    name: "Butter Chicken",
    category: "Indian",
    region: "Asia",
    course: "main",
    description: "Tender chicken in rich tomato-butter curry sauce.",
    price: "$16",
    image: "",
    dietary: [],
    customizations: ["Mild/Medium/Spicy", "Naan/Rice", "Extra Sauce"],
  },
  {
    id: 9,
    name: "Mango Sticky Rice",
    category: "Thai Dessert",
    region: "Asia",
    course: "dessert",
    description: "Sweet sticky rice served with ripe mango and coconut cream.",
    price: "$11",
    image: "",
    dietary: ["vegetarian", "gluten-free"],
    customizations: ["Extra Mango", "Sesame", "Warm Coconut Cream"],
  },
  {
    id: 10,
    name: "Mochi Trio",
    category: "Japanese Dessert",
    region: "Asia",
    course: "dessert",
    description: "Soft mochi assortment with vanilla, strawberry, and cocoa fillings.",
    price: "$10",
    image: "",
    dietary: ["vegetarian"],
    customizations: ["Flavor Mix", "Extra Dusting", "No Cocoa"],
  },
  {
    id: 11,
    name: "Lychee Jasmine Fizz",
    category: "Asian Drink",
    region: "Asia",
    course: "drink",
    description: "Sparkling jasmine tea with lychee and citrus peel.",
    price: "$7",
    image: "",
    dietary: ["non-alcoholic", "gluten-free"],
    customizations: ["Less Sweet", "Extra Mint", "No Soda"],
  },
  {
    id: 12,
    name: "Thai Iced Tea",
    category: "Asian Drink",
    region: "Asia",
    course: "drink",
    description: "Creamy Thai tea with star anise and crushed ice.",
    price: "$7",
    image: "",
    dietary: ["non-alcoholic"],
    customizations: ["Less Sweet", "Oat/Whole Milk", "No Ice"],
  },

  // Europe
  {
    id: 13,
    name: "Pasta Carbonara",
    category: "Italian",
    region: "Europe",
    course: "main",
    description: "Roman pasta with pecorino, egg yolk, and black pepper.",
    price: "$16",
    image: "/images/menu/pasta-carbonara.jpg",
    dietary: [],
    customizations: ["Guanciale/Bacon", "Extra Cheese", "Pepper Level"],
  },
  {
    id: 14,
    name: "Grilled Branzino",
    category: "Mediterranean",
    region: "Europe",
    course: "main",
    description: "Whole fish grilled with lemon, herbs, and olive oil.",
    price: "$24",
    image: "/images/menu/grilled-branzino.jpg",
    dietary: ["gluten-free"],
    customizations: ["Whole/Filleted", "Lemon/Lime", "Extra Herbs"],
  },
  {
    id: 15,
    name: "Chocolate Cake Slice",
    category: "European Dessert",
    region: "Europe",
    course: "dessert",
    description: "Layered chocolate cake with ganache and berry garnish.",
    price: "$10",
    image: "",
    dietary: ["vegetarian"],
    customizations: ["Extra Ganache", "Berry Compote", "No Nuts"],
  },
  {
    id: 16,
    name: "Tiramisu",
    category: "Italian Dessert",
    region: "Europe",
    course: "dessert",
    description: "Mascarpone cream layered with espresso-soaked sponge.",
    price: "$9",
    image: "",
    dietary: ["vegetarian"],
    customizations: ["Extra Cocoa", "Low Alcohol", "Amaretto"],
  },
  {
    id: 17,
    name: "Sangria Spritz",
    category: "European Cocktail",
    region: "Europe",
    course: "drink",
    description: "Light red wine spritz with citrus and berries.",
    price: "$11",
    image: "",
    dietary: ["alcoholic"],
    customizations: ["Dry/Semi-Sweet", "Extra Citrus", "No Soda"],
  },
  {
    id: 18,
    name: "Citrus Rosemary Tonic",
    category: "European Drink",
    region: "Europe",
    course: "drink",
    description: "Citrus tonic infused with rosemary and orange peel.",
    price: "$7",
    image: "",
    dietary: ["non-alcoholic", "gluten-free"],
    customizations: ["Less Sweet", "Extra Rosemary", "No Ice"],
  },

  // Middle East
  {
    id: 19,
    name: "Shawarma Wrap",
    category: "Levant",
    region: "Middle East",
    course: "main",
    description: "Marinated chicken wrap with tahini and fresh crunch.",
    price: "$12",
    image: "/images/menu/chicken-shawarma.jpg",
    dietary: ["vegetarian-option"],
    customizations: ["Chicken/Lamb/Vegetarian", "Extra Tahini", "Spicy Sauce"],
  },
  {
    id: 20,
    name: "Falafel Plate",
    category: "Levant",
    region: "Middle East",
    course: "main",
    description: "Crisp falafel with hummus, salad, and warm pita.",
    price: "$10",
    image: "/images/menu/falafel-plate.jpg",
    dietary: ["vegetarian", "vegan"],
    customizations: ["Extra Tahini", "Spicy", "No Pita"],
  },
  {
    id: 21,
    name: "Baklava",
    category: "Middle Eastern Dessert",
    region: "Middle East",
    course: "dessert",
    description: "Layered pastry with pistachio and honey syrup.",
    price: "$9",
    image: "",
    dietary: ["vegetarian"],
    customizations: ["Walnut/Pistachio", "Extra Honey", "No Clove"],
  },
  {
    id: 22,
    name: "Date Pistachio Cake",
    category: "Middle Eastern Dessert",
    region: "Middle East",
    course: "dessert",
    description: "Soft date cake topped with pistachio crumble and cream.",
    price: "$10",
    image: "",
    dietary: ["vegetarian"],
    customizations: ["Extra Pistachio", "Date Syrup", "No Cream"],
  },
  {
    id: 23,
    name: "Mint Lemonade",
    category: "Middle Eastern Drink",
    region: "Middle East",
    course: "drink",
    description: "Fresh lemon and mint cooler over crushed ice.",
    price: "$6",
    image: "",
    dietary: ["non-alcoholic", "vegan", "gluten-free"],
    customizations: ["Less Sweet", "Extra Mint", "No Ice"],
  },
  {
    id: 24,
    name: "Arak Citrus Highball",
    category: "Middle Eastern Cocktail",
    region: "Middle East",
    course: "drink",
    description: "Anise spirit highball with grapefruit and sparkling water.",
    price: "$12",
    image: "",
    dietary: ["alcoholic"],
    customizations: ["Strong/Light", "Extra Citrus", "No Soda"],
  },

  // Americas
  {
    id: 25,
    name: "Lomo Saltado",
    category: "Peruvian",
    region: "Americas",
    course: "main",
    description: "Wok-seared beef strips with tomato, onion, and fries.",
    price: "$21",
    image: "",
    dietary: [],
    customizations: ["Beef/Chicken", "Rice/Quinoa", "Extra Aji"],
  },
  {
    id: 26,
    name: "Brazilian Moqueca",
    category: "Brazilian",
    region: "Americas",
    course: "main",
    description: "Seafood stew with coconut milk, peppers, and palm oil.",
    price: "$23",
    image: "",
    dietary: ["gluten-free"],
    customizations: ["Fish/Shrimp/Mixed", "Extra Cilantro", "Light Coconut"],
  },
  {
    id: 27,
    name: "Tres Leches Slice",
    category: "Latin Dessert",
    region: "Americas",
    course: "dessert",
    description: "Milk-soaked sponge cake with vanilla cream.",
    price: "$10",
    image: "",
    dietary: ["vegetarian"],
    customizations: ["Berry Compote", "Cinnamon Dust", "Extra Cream"],
  },
  {
    id: 28,
    name: "Butter Cookies Assortment",
    category: "American Dessert",
    region: "Americas",
    course: "dessert",
    description: "House-baked butter cookies in vanilla and cocoa selection.",
    price: "$9",
    image: "",
    dietary: ["vegetarian"],
    customizations: ["Vanilla/Cocoa Mix", "Extra Crunch", "No Sugar Dust"],
  },
  {
    id: 29,
    name: "Classic Margarita",
    category: "American Cocktail",
    region: "Americas",
    course: "drink",
    description: "Tequila, lime, and orange liqueur with sea-salt rim.",
    price: "$12",
    image: "",
    dietary: ["alcoholic"],
    customizations: ["Frozen/On Ice", "Salt/No Salt", "Spicy Rim"],
  },
  {
    id: 30,
    name: "Hibiscus Ginger Tonic",
    category: "American Drink",
    region: "Americas",
    course: "drink",
    description: "Hibiscus tonic with ginger, lime, and aromatic bitters.",
    price: "$7",
    image: "",
    dietary: ["non-alcoholic", "gluten-free"],
    customizations: ["Less Sweet", "Extra Ginger", "No Bitters"],
  },
]

export const featuredMenuItems = menuItems.filter((item) => Boolean(item.image)).slice(0, 8)
